"""empty message

Revision ID: 1ef3a28b8866
Revises: 25e49f018f17
Create Date: 2025-01-07 20:32:35.363878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ef3a28b8866'
down_revision = '25e49f018f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gestor_citas', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('servicio',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_empresa_id_fkey', type_='foreignkey')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_empresa_id_fkey', 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('servicio',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('gestor_citas', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
